strings:
  appName: ATD Хлебница
  title: TweedleDo Хлебница
  description: TweedleDo Хлебница - список покупок от artyhedgehog
  searchBar.placeholder: Что нужно купить?
  footer.archiveCompleted: Забрать купленное
  todoItem.unarchive: Кончилось
  menu.data: Экспортировать/импортировать данные
  menu.tweedledo: На сайт TweedleDo

lists:
  - id: groceries
    label: Продукты
  - id: pharmacy
    label: Аптека
  - id: misc
    label: Разное
  - id: tea
    label: Чай
  - id: books
    label: Книги

menu:
  topLevelItemsLimit: 3

states:
  - id: stock
    label: Запасы
    filter: archived
    hash: '#/archived'
  - id: shop
    label: В магазин!
    filter: all
    hash: '#/'
  - id: buy
    label: Купить
    filter: active
    hash: '#/active'
  - id: cart
    label: Корзина
    filter: completed
    hash: '#/completed'

filters:
  all:
    value: archived eq false
  active:
    value: completed eq false and archived eq false
  completed:
    value: completed eq true and archived eq false
  archived:
    value: archived eq true
